portfolio: Your Name

theme: light
patternImage: circuit.svg

socialMedia:
  - name: GitHub
    url: https://github.com/
    image: github.svg

  - name: Twitter
    url: https://twitter.com/
    image: twitter.svg

projects:
  - name: About Me
    url: https://filipesantoscorrea.com/
    image: about-me.svg

  - name: Snake
    url: https://safi1012.github.io/ResponsiveSnake/
    image: responsive-snake.png

  - name: Shrink Me
    url: https://shrinkme.app
    image: shrink-me.svg
    backgroundColor: \#fefefe

terms:
  name: 'Your name'
  website: 'https://crafted.link'

privacy:
  name: 'Your name'
  address: 'Your address'
  mail: 'your-mail@address.com'
  phone: 'Your number e.g. +1-123-456-7890'
