theme: light

sorting: order # alphabetical | order | random

socialMedia:
  - name: GitHub
    url: https://github.com/Safi1012
    icon: assets/icons/social-media/github.svg

  - name: Twitter
    url: https://twitter.com/Safi1012
    icon: assets/icons/social-media/twitter.svg

projects:
  - name: Shrink Me
    url: https://shrinkme.app
    icon: assets/icons/projects/shrink-me.svg
    background-color: #48bfcd
    
  - name: Bitcoin
    url: https://github.com/Safi1012/bitcoin
    icon: assets/icons/projects/bitcoin.png
    background-color:
