portfolio: Filipe's Portfolio

theme: light

socialMedia:
  - name: GitHub
    url: https://github.com/Safi1012

  - name: Twitter
    url: https://twitter.com/Safi1012

projects:
  - name: Shrink Me
    url: https://shrinkme.app
    image: shrink-me.svg
    backgroundColor: FFF

  - name: Snake
    url: https://github.com/Safi1012/bitcoin
    image: responsive-snake.png
    backgroundColor: FFF

  - name: About Me
    url: https://github.com/Safi1012/filipesantoscorrea.com
    image: about-me.svg
    backgroundColor: FBFBFB

  - name: Bitcoin
    url: https://github.com/Safi1012/bitcoin
    image: bitcoin.png
    backgroundColor: FFF

# 
# possible options: 'pattern' and 'gradient'
# 
backgroundType: pattern

patternImage: circuit-board.svg
