portfolio: Filipe's Portfolio

theme: light

socialMedia:
  - name: GitHub
    url: https://github.com/Safi1012

  - name: Twitter
    url: https://twitter.com/Safi1012

projects:
  - name: Shrink Me
    url: https://shrinkme.app
    icon: assets/icons/projects/shrink-me.svg
    backgroundColor:

  - name: Snake
    url: https://github.com/Safi1012/bitcoin
    icon: assets/icons/projects/responsive-snake.png
    backgroundColor:

  - name: About Me
    url: https://github.com/Safi1012/filipesantoscorrea.com
    icon: assets/icons/projects/about-me.svg
    backgroundColor:

  - name: Bitcoin
    url: https://github.com/Safi1012/bitcoin
    icon: assets/icons/projects/bitcoin.png
    backgroundColor:

# 
# possible options: 'pattern' and 'gradient'
# 
backgroundType: pattern

gradient:
  direction: right
  firstColor: FFF
  secondColor: D6F2FF

pattern:
  type: circuit-board.svg
  color: FFF
